version: "3"
services:
  nginx:
    build:
      context: ./docker/stream-nginx
      dockerfile: Dockerfile
    
    container_name: nginx-stream.syuuta.net
    ports:
      - "1935:1935"
    volumes:
      # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
      - ./stream.conf:/etc/nginx/conf.d/stream.conf
    tty: true
    restart: always

    command: nginx -g "daemon off;"
