version: "3"
services:
  nginx:
    build:
      context: ./docker/stream-nginx
      dockerfile: Dockerfile
    
    container_name: nginx-stream.syuuta.net
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
      - ./stream.conf:/etc/nginx/conf.d/stream.conf
      - ./html:/usr/local/nginx/html/
      - /var/log/rtmp_access.log:/var/log/rtmp_access.log
    tty: true
    restart: always

    command: nginx -g "daemon off;"
